server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/workstudyms?use_Unicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #redis
  redis:
    host: 127.0.0.1
    port: 6381
    password: 123456
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        min-idle: 0
        max-wait: 2000

#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  target-bean-name: shiroFilter
  target-filter-lifecycle: true
  anon-urls:
    - /login
    - /getVerificationCode
    - /uploadFile
    - /showImageByPath
    - /student
  authc-urls:
    - /**

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl